version: "2"

services:
  web:
    restart: always
    build: ./web
    hostname: web
    environment:
      - TZ=Asia/Taipei
    ports:
      - "3000:3000"
    container_name: web
    command: bash -c 'node server'
    logging:
      driver: json-file
      options:
        max-size: 50m

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:8080"
    logging:
      driver: json-file
      options:
        max-size: 50m