version: "2"

services:
  web:
    restart: always
    build: ./web
    hostname: web
    environment:
      - TZ=Asia/Taipei
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
    container_name: web
    command: bash -c 'node server'
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default-net

  nginx:
    restart: always
    image: nginx
    container_name: nginx
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
        max-size: 50m
    networks:
      - default-net

  db:
    image: mariadb:10.2
    hostname: db
    container_name: db
    environment:
      - TZ=Asia/Taipei
      - MYSQL_ROOT_PASSWORD=1qaz2wsx
      - MYSQL_DATABASE=db
      - MYSQL_USER=david
      - MYSQL_PASSWORD=1qaz2wsx
    ports:
      - "3306:3306"
    logging:
      driver: json-file
      options:
        max-size: 50m
    restart: always
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - default-net

networks:
  default-net: